---
title: 'Lake Erie HABs Time Series'
output: html_document
---
  


```{r load libraries, warning = FALSE, message = FALSE, echo = FALSE}
#Load libraries
library(phyloseq)
library(ggplot2)
library(dplyr)
library(scales)
library(reshape2)
library(RColorBrewer)
library(vegan)
library(magrittr)
library(grid)
library(ape)
source("habs_functions.R")
source("miseqR.R")
library(mvtsplot)
theme_set(theme_bw())
```

```{r mothur import, echo = FALSE}

# Import mothur files and sample metadata
sharedfile = "mothur/allhabs.shared"
taxfile = "mothur/allhabs.taxonomy"
mapfile = "other/habs_metadata.csv"

mothurdata <- import_mothur(mothur_shared_file = sharedfile, 
                      mothur_constaxonomy_file = taxfile)

# Add the OTU number as a column in the taxonomy file
tax_table(mothurdata) <- cbind(tax_table(mothurdata), 
                         row.names(tax_table(mothurdata)))

# Rename the taxonomy columns
colnames(tax_table(mothurdata)) <- c("Kingdom", "Phylum", "Class", "Order", 
                               "Family", "Genus", "Species")

# Import sample metadata
map <- read.csv(mapfile)
map <- sample_data(map)
rownames(map) <- map$SampleID

# Merge mothurdata object with sample metadata
# Filter out non-samples (i.e. water,mock) and samples from intensive cruises.
# Filter out non-bacteria, chloroplasts and mitochondria
erie <-
  mothurdata %>%
    merge_phyloseq(map) %>%
    subset_samples(Type == "sample") %>%
    subset_taxa(Kingdom == "Bacteria" & Family != "mitochondria" & Class != "Chloroplast")

# Prune out taxa which were only present in removed samples
erie <- prune_taxa(taxa_sums(erie) > 0, erie)

# Clean this large object out
rm(mothurdata)
```

```{r echo=FALSE}
stackbar_theme <- theme(
  axis.title.x = element_text(size = 16,face = "bold"),
  axis.text.x = element_text(angle = 50, 
                             face = "bold", 
                             vjust = 1, 
                             hjust = 1, 
                             size = 15),
  axis.text.y = element_text(colour = "black", size = 10),
  axis.title.y = element_text(face = "bold", size = 16),
  plot.title = element_text(face = "bold", size = 22),
  legend.title = element_text(face = "bold", size = 16),
  legend.text = element_text(size = 14),
  strip.text.x = element_text(size = 16, face = "bold"),
  strip.text.y = element_text(size = 16, face = "bold"),
  strip.background = element_rect(color = "white",size = 2, fill = NA),
  panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.border = element_rect(colour = "black", fill = NA, size = 1.5),
  panel.margin = unit(1, "lines")
)


phylum.colors <- c("#CBD588", "#5F7FC7", "orange", "#DA5724", "#89C5DA",
                   "#508578", "#CD9BCD", "#74D944", "#D7C1B1", "#AD6F3B", "#673770","#D14285",
                   "#689030", "#6DDE88", "#652926", "#7FDCC0", "#C84248", "#8569D5", "#5E738F",
                   "#D1A33D", "#8A7C64", "#599861"
)
```


```{r echo=FALSE}
thresh = 0.0001
n = 15000

CNA.scale <-
  erie %>%
  subset_samples(Fraction == "CNA") %>%
  scale_reads(n =  n, round = "round") 


# Prune low abundance taxa
tax_mean <- taxa_sums(CNA.scale)/nsamples(CNA.scale)
CNA.scale.prune <- prune_taxa(tax_mean > thresh*n, CNA.scale)





```

# Cyanobacteria
```{r echo=FALSE}

# Cyanobacteria: subset and separate otu table
cyanos <-
  CNA.scale.prune %>%
  subset_taxa(Class == "Cyanobacteria") 
  
 
clust_func <- function(data, taxrank, cut){
  
  data.otu <- t(otu_table(data))
  
  data.otu <- scale(data.otu)
  
  colnames(data.otu) <- paste(tax_table(data)[ ,taxrank], 
                              tax_table(data)[ ,"Species"])
  
 
  d <- vegdist(t(data.otu), method = "euclidean")


  data.clust <- hclust(d = d, method = "complete")
  
  cols <- cutree(data.clust, cut)

  plot(as.phylo(data.clust), tip.color = cols)
  
  data <- data.frame(data.otu)
  data <- data[ ,data.clust$order]
  
  newcols <- cols[data.clust$order]
  
  return(list(data = data, cols = newcols))
  
} 
```

## Station 2
```{r echo = FALSE}
# WE 2

cyanos.we2 <- 
  cyanos %>%
  subset_samples(Station == "WE2") 
 

cyanos.we2.clust <- clust_func(cyanos.we2, "Genus", 3)

mvtsplot(x = cyanos.we2.clust$data, levels = 3, main = "Station WE2", smooth.df = 6, group = cyanos.we2.clust$cols, rowstat = median)

k <- kmeans(t(cyanos.we2.clust$data), centers = 3)

print(k$cluster)


m <- t(as.matrix(cyanos.we2.clust$data))
heatmap(x = m,Colv = NA)
```

## Station 12
```{r echo = FALSE}

# WE 12
cyanos.we12 <- 
  cyanos %>%
  subset_samples(Station == "WE12")

cyanos.we12.clust <- clust_func(cyanos.we12, "Genus", 4)

mvtsplot(x = cyanos.we12.clust$data, levels = 3, main = "Station WE12", smooth.df = 6,
         group = cyanos.we12.clust$cols)
```

## Station 4
```{r echo = FALSE}

# WE 4
cyanos.we4 <- 
  cyanos %>%
  subset_samples(Station == "WE4")

cyanos.we4.clust <- clust_func(cyanos.we4, "Genus", 4)

mvtsplot(x = cyanos.we4.clust$data, levels = 3, main = "Station WE4", smooth.df = 3,
         group = cyanos.we4.clust$cols, margin=FALSE)




```


# Heterotrophs

```{r echo=FALSE}

thresh = 0.001

# Prune low abundance taxa
tax_mean <- taxa_sums(CNA.scale)/nsamples(CNA.scale)
CNA.scale.prune <- prune_taxa(tax_mean > thresh*n, CNA.scale)

# Heterotrophs: subset and separate otu table
htrophs <-
  CNA.scale.prune %>%
  subset_taxa(Class != "Cyanobacteria") 
```

## Station 2
```{r echo = FALSE}


# WE 2
htrophs.we2 <- 
  htrophs %>%
  subset_samples(Station == "WE2") 
 

htrophs.we2.clust <- clust_func(htrophs.we2, "Phylum", 3)

mvtsplot(x = htrophs.we2.clust$data, levels = 3, main = "Station WE2", smooth.df = 8, group = htrophs.we2.clust$cols)

k <- kmeans(t(htrophs.we2.clust$data), centers = 3)
```

# Station 12
```{r echo = FALSE}

# WE 12
htrophs.we12 <- 
  htrophs %>%
  subset_samples(Station == "WE12")

htrophs.we12.clust <- clust_func(htrophs.we12, "Phylum", 4)

mvtsplot(x = htrophs.we12.clust$data, levels = 3, main = "Station WE12", smooth.df = 8, group = htrophs.we12.clust$cols)
```

## Station 4
```{r echo = FALSE}
# WE 4
htrophs.we4 <- 
  htrophs %>%
  subset_samples(Station == "WE4")

htrophs.we4.clust <- clust_func(htrophs.we4, "Phylum", 5)

mvtsplot(x = htrophs.we4.clust$data, levels = 3, main = "Station WE4", smooth.df = 8, group = htrophs.we4.clust$cols, margin = FALSE)


```